-- AlterTable
ALTER TABLE `Crypto` ADD COLUMN `last1Value` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `last2Value` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `last3Value` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `lastValue` DOUBLE NOT NULL DEFAULT 0;
